<?php
/**
 * Created by PhpStorm.
 * User: 老王专用
 * Date: 2019/4/15
 * Time: 17:17
 */

namespace app\api\model;



class User extends BaseModel
{
    protected $user_id;
    public function initialize()
    {
        $this->user_id = 1;
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    protected $hidden = ["id","openid","create_time","update_time"];
    public function getByOpenID($openid){
        return $this->where('openid','=',$openid)
            ->find();
    }
    public function setMotto($motto){
        self::where("id","=",$this->user_id)
            ->update([
                'motto' => $motto,
            ]);
        return $motto;
    }
}